site_name: Gulp-PHP-Minify
site_description: Gulp plug-in minifying PHP source code by removing comments and whitespace.
site_author: Cédric Belin - cedric@belin.io
site_url: https://docs.belin.io/gulp-php-minify

docs_dir: ../doc
site_dir: ../www

repo_name: git.belin.io
repo_url: https://git.belin.io/cedx/gulp-php-minify
edit_uri: ""

copyright: Copyright &copy; 2016 - 2020 Cédric Belin
extra:
  social:
    - icon: fontawesome/solid/globe
      link: "https://belin.io"
      name: Belin.io
    - icon: fontawesome/brands/github
      link: "https://github.com/cedx"
      name: GitHub
    - icon: fontawesome/brands/twitter
      link: "https://twitter.com/cedxbelin"
      name: Twitter
    - icon: fontawesome/brands/linkedin
      link: "https://linkedin.com/in/cedxbelin"
      name: LinkedIn

markdown_extensions:
  - admonition
  - codehilite
  - meta
  - toc:
      permalink: true

nav:
  - Overview: index.md
  - Installation: installation.md
  - Usage: usage.md
  - About:
      - License: about/license.md
      - See also: about/see_also.md

theme:
  favicon: img/favicon.ico
  features:
    - instant
  icon:
    logo: fontawesome/solid/book-reader
    repo: fontawesome/brands/git-alt
  name: material
  palette:
    accent: red
    primary: red
